from unittest_reinvent.running_modes.transfer_learning_tests.test_transfer_learning import TestTransferLearning
from unittest_reinvent.running_modes.transfer_learning_tests.test_link_invent_transfer_learning import \
    TestLinkInventTransferLearning
from unittest_reinvent.running_modes.transfer_learning_tests.test_mol2mol_transfer_learning import TestMol2MolTransferLearning
